{
  "_args": [
    [
      "react-try-catch-render@1.0.0",
      "C:\\Users\\Tiger\\Desktop\\react\\LearnReactDemo-master\\LearnReactDemo-master\\redux-demo"
    ]
  ],
  "_from": "react-try-catch-render@1.0.0",
  "_id": "react-try-catch-render@1.0.0",
  "_inBundle": false,
  "_integrity": "sha1-XI2lEkeWpapsmNT2xI4nM1X1W6c=",
  "_location": "/react-try-catch-render",
  "_phantomChildren": {},
  "_requested": {
    "type": "version",
    "registry": true,
    "raw": "react-try-catch-render@1.0.0",
    "name": "react-try-catch-render",
    "escapedName": "react-try-catch-render",
    "rawSpec": "1.0.0",
    "saveSpec": null,
    "fetchSpec": "1.0.0"
  },
  "_requiredBy": [
    "/"
  ],
  "_resolved": "https://registry.npmjs.org/react-try-catch-render/-/react-try-catch-render-1.0.0.tgz",
  "_spec": "1.0.0",
  "_where": "C:\\Users\\Tiger\\Desktop\\react\\LearnReactDemo-master\\LearnReactDemo-master\\redux-demo",
  "author": {
    "name": "Georgi Kosharov"
  },
  "bugs": {
    "url": "https://github.com/gkosharov/react-try-catch-render/issues"
  },
  "description": "React try cahtch catches errors inside React components render",
  "devDependencies": {
    "babel-cli": "^6.3.17",
    "babel-core": "^6.3.21",
    "babel-preset-es2015": "^6.3.3",
    "babel-preset-stage-0": "^6.3.13"
  },
  "files": [
    "lib",
    "src"
  ],
  "homepage": "https://github.com/gkosharov/react-try-catch-render#readme",
  "keywords": [
    "react",
    "reactjs",
    "errors"
  ],
  "license": "MIT",
  "main": "lib/index.js",
  "name": "react-try-catch-render",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/gkosharov/react-try-catch-render.git"
  },
  "scripts": {
    "build": "babel src --out-dir lib",
    "prepublish": "npm run build",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "version": "1.0.0"
}
